/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashSubscriptionRouteImport } from './routes/_dash.subscription'
import { Route as DashResellersRouteImport } from './routes/_dash.resellers'
import { Route as DashLicensesRouteImport } from './routes/_dash.licenses'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSubscriptionRoute = DashSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashRoute,
} as any)
const DashResellersRoute = DashResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => DashRoute,
} as any)
const DashLicensesRoute = DashLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/dashboard': typeof DashDashboardRoute
  '/licenses': typeof DashLicensesRoute
  '/resellers': typeof DashResellersRoute
  '/subscription': typeof DashSubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/dashboard': typeof DashDashboardRoute
  '/licenses': typeof DashLicensesRoute
  '/resellers': typeof DashResellersRoute
  '/subscription': typeof DashSubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/upgrade': typeof UpgradeRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/licenses': typeof DashLicensesRoute
  '/_dash/resellers': typeof DashResellersRoute
  '/_dash/subscription': typeof DashSubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/upgrade'
    | '/dashboard'
    | '/licenses'
    | '/resellers'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/upgrade'
    | '/dashboard'
    | '/licenses'
    | '/resellers'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/upgrade'
    | '/_dash/dashboard'
    | '/_dash/licenses'
    | '/_dash/resellers'
    | '/_dash/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  UpgradeRoute: typeof UpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/subscription': {
      id: '/_dash/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof DashSubscriptionRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/resellers': {
      id: '/_dash/resellers'
      path: '/resellers'
      fullPath: '/resellers'
      preLoaderRoute: typeof DashResellersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/licenses': {
      id: '/_dash/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof DashLicensesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashDashboardRoute: typeof DashDashboardRoute
  DashLicensesRoute: typeof DashLicensesRoute
  DashResellersRoute: typeof DashResellersRoute
  DashSubscriptionRoute: typeof DashSubscriptionRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashDashboardRoute: DashDashboardRoute,
  DashLicensesRoute: DashLicensesRoute,
  DashResellersRoute: DashResellersRoute,
  DashSubscriptionRoute: DashSubscriptionRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  UpgradeRoute: UpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
