/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as DashUpgradeAdminRouteImport } from './routes/_dash.upgrade-admin'
import { Route as DashTutorialsRouteImport } from './routes/_dash.tutorials'
import { Route as DashTelegramBotRouteImport } from './routes/_dash.telegram-bot'
import { Route as DashResellersRouteImport } from './routes/_dash.resellers'
import { Route as DashMyLicenseRouteImport } from './routes/_dash.my-license'
import { Route as DashLicensesRouteImport } from './routes/_dash.licenses'
import { Route as DashIntegrationsRouteImport } from './routes/_dash.integrations'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as ApiPublicUpgradeZipRouteImport } from './routes/api/public/upgrade-zip'
import { Route as ApiPublicUpgradeMetaRouteImport } from './routes/api/public/upgrade-meta'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashUpgradeAdminRoute = DashUpgradeAdminRouteImport.update({
  id: '/upgrade-admin',
  path: '/upgrade-admin',
  getParentRoute: () => DashRoute,
} as any)
const DashTutorialsRoute = DashTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => DashRoute,
} as any)
const DashTelegramBotRoute = DashTelegramBotRouteImport.update({
  id: '/telegram-bot',
  path: '/telegram-bot',
  getParentRoute: () => DashRoute,
} as any)
const DashResellersRoute = DashResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => DashRoute,
} as any)
const DashMyLicenseRoute = DashMyLicenseRouteImport.update({
  id: '/my-license',
  path: '/my-license',
  getParentRoute: () => DashRoute,
} as any)
const DashLicensesRoute = DashLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => DashRoute,
} as any)
const DashIntegrationsRoute = DashIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const ApiPublicUpgradeZipRoute = ApiPublicUpgradeZipRouteImport.update({
  id: '/api/public/upgrade-zip',
  path: '/api/public/upgrade-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUpgradeMetaRoute = ApiPublicUpgradeMetaRouteImport.update({
  id: '/api/public/upgrade-meta',
  path: '/api/public/upgrade-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/dashboard': typeof DashDashboardRoute
  '/integrations': typeof DashIntegrationsRoute
  '/licenses': typeof DashLicensesRoute
  '/my-license': typeof DashMyLicenseRoute
  '/resellers': typeof DashResellersRoute
  '/telegram-bot': typeof DashTelegramBotRoute
  '/tutorials': typeof DashTutorialsRoute
  '/upgrade-admin': typeof DashUpgradeAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/upgrade-meta': typeof ApiPublicUpgradeMetaRoute
  '/api/public/upgrade-zip': typeof ApiPublicUpgradeZipRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/dashboard': typeof DashDashboardRoute
  '/integrations': typeof DashIntegrationsRoute
  '/licenses': typeof DashLicensesRoute
  '/my-license': typeof DashMyLicenseRoute
  '/resellers': typeof DashResellersRoute
  '/telegram-bot': typeof DashTelegramBotRoute
  '/tutorials': typeof DashTutorialsRoute
  '/upgrade-admin': typeof DashUpgradeAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/upgrade-meta': typeof ApiPublicUpgradeMetaRoute
  '/api/public/upgrade-zip': typeof ApiPublicUpgradeZipRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/integrations': typeof DashIntegrationsRoute
  '/_dash/licenses': typeof DashLicensesRoute
  '/_dash/my-license': typeof DashMyLicenseRoute
  '/_dash/resellers': typeof DashResellersRoute
  '/_dash/telegram-bot': typeof DashTelegramBotRoute
  '/_dash/tutorials': typeof DashTutorialsRoute
  '/_dash/upgrade-admin': typeof DashUpgradeAdminRoute
  '/r/$slug': typeof RSlugRoute
  '/api/public/upgrade-meta': typeof ApiPublicUpgradeMetaRoute
  '/api/public/upgrade-zip': typeof ApiPublicUpgradeZipRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/upgrade'
    | '/dashboard'
    | '/integrations'
    | '/licenses'
    | '/my-license'
    | '/resellers'
    | '/telegram-bot'
    | '/tutorials'
    | '/upgrade-admin'
    | '/r/$slug'
    | '/api/public/upgrade-meta'
    | '/api/public/upgrade-zip'
    | '/api/public/mercadopago/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/upgrade'
    | '/dashboard'
    | '/integrations'
    | '/licenses'
    | '/my-license'
    | '/resellers'
    | '/telegram-bot'
    | '/tutorials'
    | '/upgrade-admin'
    | '/r/$slug'
    | '/api/public/upgrade-meta'
    | '/api/public/upgrade-zip'
    | '/api/public/mercadopago/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/signup'
    | '/upgrade'
    | '/_dash/dashboard'
    | '/_dash/integrations'
    | '/_dash/licenses'
    | '/_dash/my-license'
    | '/_dash/resellers'
    | '/_dash/telegram-bot'
    | '/_dash/tutorials'
    | '/_dash/upgrade-admin'
    | '/r/$slug'
    | '/api/public/upgrade-meta'
    | '/api/public/upgrade-zip'
    | '/api/public/mercadopago/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UpgradeRoute: typeof UpgradeRoute
  RSlugRoute: typeof RSlugRoute
  ApiPublicUpgradeMetaRoute: typeof ApiPublicUpgradeMetaRoute
  ApiPublicUpgradeZipRoute: typeof ApiPublicUpgradeZipRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/upgrade-admin': {
      id: '/_dash/upgrade-admin'
      path: '/upgrade-admin'
      fullPath: '/upgrade-admin'
      preLoaderRoute: typeof DashUpgradeAdminRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tutorials': {
      id: '/_dash/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof DashTutorialsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/telegram-bot': {
      id: '/_dash/telegram-bot'
      path: '/telegram-bot'
      fullPath: '/telegram-bot'
      preLoaderRoute: typeof DashTelegramBotRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/resellers': {
      id: '/_dash/resellers'
      path: '/resellers'
      fullPath: '/resellers'
      preLoaderRoute: typeof DashResellersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/my-license': {
      id: '/_dash/my-license'
      path: '/my-license'
      fullPath: '/my-license'
      preLoaderRoute: typeof DashMyLicenseRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/licenses': {
      id: '/_dash/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof DashLicensesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/integrations': {
      id: '/_dash/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof DashIntegrationsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/public/upgrade-zip': {
      id: '/api/public/upgrade-zip'
      path: '/api/public/upgrade-zip'
      fullPath: '/api/public/upgrade-zip'
      preLoaderRoute: typeof ApiPublicUpgradeZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upgrade-meta': {
      id: '/api/public/upgrade-meta'
      path: '/api/public/upgrade-meta'
      fullPath: '/api/public/upgrade-meta'
      preLoaderRoute: typeof ApiPublicUpgradeMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteChildren {
  DashDashboardRoute: typeof DashDashboardRoute
  DashIntegrationsRoute: typeof DashIntegrationsRoute
  DashLicensesRoute: typeof DashLicensesRoute
  DashMyLicenseRoute: typeof DashMyLicenseRoute
  DashResellersRoute: typeof DashResellersRoute
  DashTelegramBotRoute: typeof DashTelegramBotRoute
  DashTutorialsRoute: typeof DashTutorialsRoute
  DashUpgradeAdminRoute: typeof DashUpgradeAdminRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashDashboardRoute: DashDashboardRoute,
  DashIntegrationsRoute: DashIntegrationsRoute,
  DashLicensesRoute: DashLicensesRoute,
  DashMyLicenseRoute: DashMyLicenseRoute,
  DashResellersRoute: DashResellersRoute,
  DashTelegramBotRoute: DashTelegramBotRoute,
  DashTutorialsRoute: DashTutorialsRoute,
  DashUpgradeAdminRoute: DashUpgradeAdminRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UpgradeRoute: UpgradeRoute,
  RSlugRoute: RSlugRoute,
  ApiPublicUpgradeMetaRoute: ApiPublicUpgradeMetaRoute,
  ApiPublicUpgradeZipRoute: ApiPublicUpgradeZipRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
